language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  
env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""
  

before_script:
    - composer self-update
    - composer update --prefer-source $PREFER_LOWEST 

matrix:
  allow_failures:
    - php: hhvm
